spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3307/autocoin_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8080

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha

jwt:
  secret: ${JWT_SECRET:your-default-jwt-secret-key-should-be-very-long-and-secure}
  expiration: ${JWT_EXPIRATION:1800000} # 30 minutes in milliseconds

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type
  max-age: 3600

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET:your-local-s3-bucket}
    credentials:
      access-key: ${AWS_ACCESS_KEY:your-local-aws-access-key}
      secret-key: ${AWS_SECRET_KEY:your-local-aws-secret-key}
    region:
      static: ${AWS_REGION:ap-northeast-2}
    stack:
      auto: false