# ====================================
# H2 테스트환경 설정
# ====================================

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop  # 테스트용 - 시작시 생성, 종료시 삭제
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
    show-sql: false  # 테스트용 - 조용함

  h2:
    console:
      enabled: true  # H2 웹 콘솔 활성화
      path: /h2-console

# 로깅 설정 (테스트용 - 간소화)
logging:
  level:
    com.autocoin: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    io.sentry: WARN
    org.springframework.test: INFO

# Swagger/OpenAPI 설정 (테스트용 - 활성화)
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# 모니터링 설정 (테스트용 - Prometheus 포함)
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 모든 엔드포인트 활성화
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true

# Sentry 설정 (테스트용 - 비활성화)
sentry:
  dsn: ""  # 테스트에서는 Sentry 비활성화
  traces-sample-rate: 0.0
  debug: false

# 테스트용 설정
test:
  database:
    cleanup: true
