global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@autocoin.com'

route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'default-receiver'
  - match:
      severity: warning
    receiver: 'default-receiver'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://localhost:5005/alerts'

- name: 'default-receiver'
  webhook_configs:
  - url: 'http://localhost:5005/alerts'
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']
