groups:
  - name: autocoin-api-alerts
    rules:
      # 애플리케이션 다운 알림
      - alert: AutocoinApiDown
        expr: up{job="autocoin-api"} == 0
        for: 30s
        labels:
          severity: critical
          service: autocoin-api
        annotations:
          summary: "Autocoin API is down"
          description: "Autocoin API has been down for more than 30 seconds."

      # 높은 응답 시간 알림
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, sum(rate(http_server_requests_duration_seconds_bucket{job="autocoin-api"}[5m])) by (le)) > 1
        for: 2m
        labels:
          severity: warning
          service: autocoin-api
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is above 1 second for more than 2 minutes."

      # 높은 에러율 알림
      - alert: HighErrorRate
        expr: sum(rate(http_server_requests_total{job="autocoin-api",status=~"5.."}[5m])) / sum(rate(http_server_requests_total{job="autocoin-api"}[5m])) > 0.05
        for: 5m
        labels:
          severity: warning
          service: autocoin-api
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 5% for more than 5 minutes."

      # 높은 메모리 사용률 알림
      - alert: HighMemoryUsage
        expr: (jvm_memory_used_bytes{job="autocoin-api",area="heap"} / jvm_memory_max_bytes{job="autocoin-api",area="heap"}) * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: autocoin-api
        annotations:
          summary: "High memory usage detected"
          description: "JVM heap memory usage is above 80% for more than 5 minutes."

      # 높은 CPU 사용률 알림
      - alert: HighCpuUsage
        expr: system_cpu_usage{job="autocoin-api"} > 0.8
        for: 5m
        labels:
          severity: warning
          service: autocoin-api
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 5 minutes."

      # 데이터베이스 연결 문제
      - alert: DatabaseConnectionFailure
        expr: hikaricp_connections_active{job="autocoin-api"} == 0
        for: 1m
        labels:
          severity: critical
          service: autocoin-api
        annotations:
          summary: "Database connection failure"
          description: "No active database connections detected."

      # 너무 많은 활성 연결
      - alert: TooManyActiveConnections
        expr: hikaricp_connections_active{job="autocoin-api"} / hikaricp_connections_max{job="autocoin-api"} > 0.9
        for: 2m
        labels:
          severity: warning
          service: autocoin-api
        annotations:
          summary: "Too many active database connections"
          description: "Database connection pool is over 90% utilized."

      # 디스크 공간 부족
      - alert: LowDiskSpace
        expr: (node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"} > 0.85
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Low disk space"
          description: "Disk space usage is above 85%."

      # Upbit API 에러율 증가
      - alert: UpbitApiHighErrorRate
        expr: increase(autocoin_api_upbit_errors_total[5m]) / increase(autocoin_api_upbit_requests_total[5m]) > 0.1
        for: 3m
        labels:
          severity: warning
          service: autocoin-api
          component: upbit-api
        annotations:
          summary: "High Upbit API error rate"
          description: "Upbit API error rate is above 10% in the last 5 minutes."
